#!/bin/bash
cp /usr/lib/ssl/openssl.cnf ./
mkdir demoCA
cd demoCA
mkdir certs crl newcerts
touch index.txt serial
echo 1000 > serial
cd ..
openssl req -new -x509 -keyout ca.key -out ca.crt -config openssl.cnf
openssl genrsa -aes128 -out server.key 1024
openssl rsa -in server.key -text
openssl req -new -key server.key -out server.csr -config openssl.cnf
openssl ca -in server.csr -out server.crt -cert ca.crt -keyfile ca.key -config openssl.cnf
sudo mkdir /var/www/sra221
sudo cp index.html /var/www/sra221
sudo cp seed-ssl.conf /etc/apache2/sites-available
sudo apachectl configtest
sudo a2enmod ssl
sudo a2ensite seed-ssl
sudo service apache2 restart
echo "127.0.0.1	sra221.com" >> /etc/hosts
